import Header from './components/header/page'
import Hero from './components/hero/page'
import Footer from './components/footer/page'

export default function HomePage(){
  return(
    <main>
      <Header/>
      <Hero/>

      <section className="homePage">
        <p className="text">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia fugit quae et perferendis blanditiis asperiores ex officiis veniam, in sed, assumenda non autem adipisci esse porro quaerat. Accusamus dolorum, nam minima praesentium, temporibus harum eum alias numquam sed tempora quia neque? Explicabo necessitatibus id labore, alias quod consequatur tempore iste impedit odit inventore ullam ratione voluptatum deleniti nam laudantium reprehenderit eius! Ab, excepturi? Dolor quibusdam, quo eveniet magnam blanditiis modi explicabo iure alias. Enim harum laborum quidem at quod animi autem tenetur explicabo quo libero, expedita provident magni inventore cumque quas et unde voluptatum. Esse minima accusamus impedit exercitationem neque.
          Consequuntur, asperiores! Corrupti ab quasi, ex quas omnis tenetur, provident odio, debitis rem voluptate repellat velit vitae eos obcaecati amet quisquam nesciunt placeat inventore nihil. Sunt possimus commodi ad enim dicta odio, temporibus dolor libero ex, voluptatum amet vel fugit ducimus exercitationem incidunt! Molestiae asperiores vel qui, tempore voluptatem dicta, labore nemo praesentium dignissimos, velit voluptates molestias fuga similique magnam facilis quia! Qui officiis quis harum cum corporis culpa iusto excepturi, quidem laboriosam eveniet error et. Consectetur ipsam delectus quos. Odio esse officia, excepturi nisi corporis maiores laboriosam, aliquam inventore, assumenda blanditiis consectetur incidunt at tenetur. Eum neque necessitatibus soluta.
          Amet dolore cumque ducimus mollitia, consequuntur rerum ut impedit. Consequatur laborum minima atque unde, eos aliquam harum tenetur accusamus ullam pariatur doloremque perferendis, omnis quo quis nemo veritatis non fuga, aspernatur veniam maxime sapiente. Obcaecati quam molestiae nisi nulla rerum eum mollitia, impedit, perspiciatis vel fuga sunt sapiente aut fugiat quas molestias vitae laudantium iure, recusandae ratione modi odio officiis inventore dolorum. Maiores mollitia cupiditate quaerat iste tempore ea blanditiis, eum, illum, eveniet aperiam beatae aut ipsa fugit iusto veniam recusandae vitae delectus. Odio reiciendis ut porro nihil iure id ratione quisquam explicabo repellat laborum, numquam asperiores consequatur. Esse, deserunt.
          Quas excepturi, nulla vitae, error perspiciatis fugiat consequuntur dicta eveniet quibusdam voluptas modi sit? Excepturi laboriosam adipisci ullam explicabo, id tempore corrupti magni cum voluptates ipsam animi in mollitia maxime autem optio inventore dolorem reprehenderit voluptate quod, est, voluptatum unde. Cumque aperiam culpa ad quae aliquid! Tempora, nihil quibusdam. Porro iste fugit corporis tempora ad maiores a aperiam, eligendi explicabo eveniet amet inventore et, ipsam laudantium natus quibusdam, eum quo. Labore assumenda quis maxime doloribus amet, dolore cupiditate illum iure quos, ipsa ex voluptatem placeat et. Sed officiis est suscipit, fugiat reiciendis dolore quos perspiciatis non aliquam officia quasi qui.
          Facere omnis mollitia aliquam explicabo debitis nisi, illum consectetur repellendus perspiciatis possimus at cumque obcaecati quaerat consequatur animi quis quisquam iste sequi et! Quidem, odit, vel expedita tempore consequuntur quas reiciendis veniam fugit tempora modi inventore odio ipsam aperiam, non deserunt? Esse accusamus voluptate reiciendis nesciunt magni dignissimos consequuntur tempora sequi enim dolores! Est quas commodi vitae? Itaque, aut sint consequuntur asperiores nobis inventore fugiat delectus porro, suscipit molestiae corrupti aliquam architecto labore nihil dolores vero sequi, mollitia ipsam autem! Rerum eaque doloribus id sapiente sequi molestias autem, eveniet, ducimus tempora, laboriosam libero ipsam. Repellendus veniam dolorem labore consequatur fugiat?
          Reiciendis facere deleniti rem deserunt perspiciatis at facilis soluta, dignissimos ullam culpa! Laudantium molestiae libero recusandae quam. Tempore totam corporis aliquid magni reprehenderit doloremque quo velit iusto nemo et nam harum accusantium voluptates laboriosam, dolorem maxime corrupti. Esse harum enim facere eos, saepe rerum ab, architecto eius inventore nesciunt tempore praesentium, molestias vero ex aliquam adipisci illum iusto! Ipsa, tempora numquam consequuntur molestiae aliquam, animi quos laborum natus sed ad beatae repellat provident ex voluptatum consequatur iure quidem voluptatibus ipsam quo dolorum quibusdam eos quis a nisi? Accusantium dolore nobis suscipit adipisci perferendis perspiciatis consectetur illum, dicta eos quos optio.
          Eos eligendi eaque nostrum? Necessitatibus assumenda exercitationem veritatis voluptas dicta ab neque in beatae vel id quasi, qui iusto dolorum labore! Iure nam odit velit repellat voluptates veniam, veritatis architecto error eveniet! Necessitatibus, amet! A, neque! Et, nisi totam! Porro minus sunt quisquam qui nobis ad aperiam sequi temporibus expedita ipsa atque neque unde, iure adipisci molestiae optio culpa. Rerum corrupti neque fugit vel temporibus esse recusandae. Nobis optio veniam illum aspernatur, commodi ducimus! Explicabo dignissimos blanditiis recusandae nobis sunt quia est tempore dolor, voluptatem nisi corporis similique ad omnis, vitae asperiores temporibus nam saepe earum optio dolorum provident! Nemo.
          Quidem quas, autem nulla similique sapiente eos nam expedita beatae labore! Dolore fugit eligendi quos, vitae obcaecati dolores aperiam amet sapiente officia non nemo eaque eius, ipsum iusto ducimus tempore. Ex, possimus. Commodi dolor exercitationem facilis! Totam, iusto expedita. Assumenda accusamus sapiente a repellendus et, harum, deserunt quaerat magni at aperiam cum adipisci itaque nostrum aliquid. Nemo dolores commodi, error praesentium dignissimos, excepturi quibusdam aspernatur velit rerum molestias rem, consequuntur odit quod recusandae suscipit earum neque ullam expedita. Odit, est nihil. Officiis non tempora omnis pariatur nemo sunt aut minima, possimus ex asperiores consequatur nostrum voluptatum, nulla voluptates libero provident?
          Minus tempora, ab voluptate eius eos illo nostrum atque accusamus praesentium sequi eveniet quaerat rem similique at vero qui nihil cumque officia, sit voluptatem iusto quisquam dolore ducimus vel. Minima beatae ullam delectus, at unde pariatur, quas dolore molestiae qui voluptate ducimus enim accusantium blanditiis? Velit architecto sed dolore illo accusamus! Quam id quisquam at voluptas numquam, beatae tempora qui eos blanditiis natus dolores accusamus assumenda iusto nihil, fuga voluptatibus ullam ipsum autem deleniti. Optio quae, harum corrupti eligendi nihil distinctio sunt quis. Repellendus vitae sed sequi rerum aspernatur expedita quis, enim assumenda odio quaerat, repudiandae officia deserunt, quae reiciendis.
          Non exercitationem perferendis, earum maxime blanditiis nemo asperiores esse recusandae eaque numquam, maiores vero sapiente, repellat magnam delectus! Saepe molestiae quis cum beatae id delectus, veniam, quas magni deleniti voluptate sequi facilis labore illo reiciendis earum autem sint perspiciatis, natus quia et dolorem? Iusto reprehenderit at itaque consequuntur explicabo ullam, illo dolore perferendis accusamus! Soluta minima harum saepe, laboriosam dolorum molestias corrupti reprehenderit facere est ad veniam. Quam ex voluptatem obcaecati commodi velit. Itaque accusantium, doloribus at, fugit officiis animi magni impedit tempore eaque iste reprehenderit qui quasi. Maiores necessitatibus recusandae ratione enim magnam aut molestias molestiae nam, unde aperiam!
        </p>
      </section>

      <Footer/>
    </main>
  )
}